server:
    servlet:
        context-path: /home
    port: 8888

spring:
    profiles:
        active: dev

house:
    location: Bucharest

philips:
    bridge:
        address: 192.168.1.169
        username: nJCp1QzRfxjkJ2GKVJYbBo0PRyQVZ5S5rTCq23Ot
    lights:
        livingroom:
            - lightstrip_livingroom_1
            - lightstrip_livingroom_2
            - hue_color_livingroom_1
            - hue_color_livingroom_2
            - hue_color_livingroom_3
        hallway:
            - lightstrip_hallway
        multimediaControl:
            - lightstrip_livingroom_1
            - lightstrip_livingroom_2
        badWeatherNotify:
            - lightstrip_hallway

tp-link:
    tapo:
        login:
            username: alex.munteanu@gmail.com
            password: v8aD364VM6XWY_W
        plugs:
            P100:
                module1:
                    address: 192.168.1.110
                module2:
                    address: 192.168.1.111
                module3:
                    address: 192.168.1.73
                module4:
                    address: 192.168.1.71

broadlink:
    a1:
        module1:
            mac: 34:ea:34:c7:61:f8
            address: 192.168.1.80
    rmpro:
        module1:
            mac: 34:ea:34:bb:1b:9c
    sp3:
        module1:
            mac: 34:ea:34:9d:2a:50
        module2:
            mac: 34:ea:34:59:6a:f7
    bridge:
        address: 192.168.1.98
        port: 9876
        protocol: http

hegel:
    h80:
        initialVolume: 30

denon:
    X4500H:
        address: 192.168.1.146

logitech:
    harmony:
        address: 192.168.1.170
        connect: false

open:
    weather:
        map:
            api:
                address: api.openweathermap.org
                cities: '{''Bucharest'':683506}'
                key: d233224e28cc867dd88f274bccbc96c0
                port: 80
                protocol: http

---

spring:
    profiles: prod, local
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        password: Home_solaris987
        url: jdbc:mariadb://192.168.1.100:3306/home_automation
        username: home
        jpa:
            hibernate:
                ddl-auto: validate

---

spring:
    profiles: dev
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
        username: sa
        jpa:
            hibernate:
                ddl-auto: update
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.H2Dialect
            show-sql: true

---

spring:
    profiles: prod
logitech:
    harmony:
        connect: true
